title = "TIMMResnet50"

[reduce_depth.phase0]
dynamic_batch_size = 2
epochs = 25
opt = "adamw"
lr = 1e-4
warmup_epochs = 0
warmup_lr = -1
enable_dimensions = ["reduce_depth"]
enable_index = [0, 1]

[reduce_depth.phase1]
dynamic_batch_size = 2
epochs = 120
opt = "adamw"
lr = 1e-4
warmup_epochs = 0
warmup_lr = -1
enable_dimensions = ["reduce_depth"]
enable_index = [0, 1, 2]

[expand_ratio.phase0]
dynamic_batch_size = 4
epochs = 25
opt = "adamw"
lr = 1e-4
warmup_epochs = 0
warmup_lr = -1
enable_dimensions = ["reduce_depth", "expand_ratio"]
enable_index = [1, 2]

[expand_ratio.phase1]
dynamic_batch_size = 4
epochs = 120
opt = "adamw"
lr = 1e-4
warmup_epochs = 5
warmup_lr = -1
enable_dimensions = ["reduce_depth", "expand_ratio"]
enable_index = [0, 1, 2]

[width_mult.phase0]
dynamic_batch_size = 4
epochs = 25
opt = "adamw"
lr = 1e-4
warmup_epochs = 0
warmup_lr = -1
enable_dimensions = ["reduce_depth", "expand_ratio", "width_mult"]
enable_index = [1, 2]

[width_mult.phase1]
dynamic_batch_size = 4
epochs = 120
opt = "adamw"
lr = 1e-4
warmup_epochs = 5
warmup_lr = -1
enable_dimensions = ["reduce_depth", "expand_ratio", "width_mult"]
enable_index = [0, 1, 2]

